# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class AlternativesFunction:
        name: str
        type: str
    class App:
        name: str
        stage: str
    class DAW-DrugSync-Function:
        name: str
        type: str
    class DrugDetailFunction:
        name: str
        type: str
    class DrugSearchAPI:
        type: str
        url: str
    class SearchFunction:
        name: str
        type: str

